### ISSUE TITLE
Raspberry pi problem with classify_audio.py

### ISSUE THREAD

**Issue by PjotrG** [google-coral/aiy-maker-kit#2]
### Description

I build the voice-controlled camera project on a raspberry pi 4 with python 3.7.3 (buster) ..everything works fine!
Now I transferred my working model to a robot in order to build a voice controlled robot working with a Rpi 3B+
the python version and also buster, when I run: 
python3 classify_audio.py --model_file ~/Downloads/converted_tflite/soundclassifier_with_metadata.tflite 
I get:
Traceback (most recent call last):
  File "classify_audio.py", line 44, in <module>
    main()
  File "classify_audio.py", line 41, in main
    audio.classify_audio(model=args.model_file, callback=handle_results)
  File "/home/pi/aiy-maker-kit/examples/aiymakerkit/audio.py", line 118, in classify_audio
    sample_rate_hz, channels = model_audio_properties(model)
  File "/home/pi/aiy-maker-kit/examples/aiymakerkit/audio.py", line 60, in model_audio_properties
    metadata_json = json.loads(displayer.get_metadata_json())
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The install seems to be o.k. (run_tests.py) and also classify_video is o.k.
What do I do wrong?
Every help is appreciated
Thanks Peter

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Operating System

Linux

### Other Devices

Raspberry Pi 3

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
You might getting empty response. Please check the [displayer output](https://github.com/google-coral/aiy-maker-kit/blob/main/aiymakerkit/audio.py#L59).

**Comment by PjotrG** [comment]
thanks hjonnala, I get an empty response from displayer.
I checked tflite_support for metadata:
on the faulty system I find 2 folders at 
/home/pi/.local/lib/python2.7/site-packages
and /home/pi/.local/lib/python3.7/site-packages
on the working system there is only one at python3.7
Is this the potential error, a comment how to correct?

**Comment by hjonnala** [comment]
I think, you have to add meta data when exporitng the tflite model. Please check with [tflite-support](https://github.com/tensorflow/tflite-support) on how to do that. Thanks!!

**Comment by PjotrG** [comment]
thanks hjonnala, I started again from scratch, reinstalled AIY Maker Kit system image and now it runs!
Don't know where the error was ?? I always used the same model file with the meta data, they seem to be o.k. Thanks again for support Peter
